### ISSUE TITLE
delete .pypirc

### ISSUE THREAD

**Issue by lovew** [harens/PyPony#3]
.pypirc has your username and password

**Comment by harens** [comment]
Hi lovew, thanks for the issue! 👍 

The reason I created a .pypirc is to integrate it with [PyPi](https://pypi.org). However, this has not been a success. I knew that anyone could see the password, that's why I just made it a random bunch of letters, with nothing to do with any other of my passwords.

Following your advice, I have deleted the file and changed the password.

Your input means a lot to me, and I thank you for raising an issue.

harens
